name: ffi_exp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  ffi: ^2.1.4
  objective_c: ^8.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  ffigen: ^19.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/test.mp3

ffigen:
  name: AVFAudio
  description: Bindings for AVFAudio.
  language: objc
  output: 'lib/avf_audio_bindings.dart'
  exclude-all-by-default: true
  objc-interfaces:
    include:
      - 'AVAudioPlayer'
      - 'NSBundle'
  headers:
    entry-points:
      - '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/AVFAudio.framework/Headers/AVAudioPlayer.h'
  preamble: |
    // Copyright (c) 2024, the Dart project authors. Please see the AUTHORS file
    // for details. All rights reserved. Use of this source code is governed by a
    // BSD-style license that can be found in the LICENSE file.

    // ignore_for_file: camel_case_types, non_constant_identifier_names, unused_element, unused_field, void_checks, annotate_overrides, no_leading_underscores_for_local_identifiers, library_private_types_in_public_api
